### ISSUE TITLE
Running westpa in parallel with multiple jobs

### ISSUE THREAD

**Issue by xiki-tempula** [westpa/westpa#133]
**Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]  

The current westpa implementation requires all the GPUs to be available when the job is executed, which might be difficult to achieve due to the infrastructure of the cluster.

**Describe the solution you'd like.** A clear and concise description of what you want to happen.  

Since the coupling between different runs are very weak, it will be very helpful if multiple calls can be executed which contribute to the same h5 file

For example, I could run two jobs on node 1 and node 2.

On node 1, w_run is executed, which reads the west.h5, select one job and mark it as running and then start this job.
At the same time, w_run is executed on node 2, which tried to select the first job but found that it has been marked, so it selects the next job, mark it as running and then start the job.

Hours later, node 1 finish the job, write the result to the west.h5 and try to select the next job, found it to be marked, goes to job 3 and then mark it and start the job.

**Comment by agrossfield** [comment]
The general version of this would be the controller submitting the jobs to a queuing system (eg slurm).

Dr. Alan Grossfield
Department of Biochemistry and Biophysics
University of Rochester Medical Center

On Oct 2, 2020, at 3:25 PM, Zhiyi Wu <notifications@github.com> wrote:

﻿

Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

The current westpa implementation requires all the GPUs to be available when the job is executed.

Describe the solution you'd like. A clear and concise description of what you want to happen.

Since the coupling between different runs are very weak, it will be very helpful if multiple calls can be executed which contribute to the same h5 file

For example, I could run two jobs on node 1 and node 2.

On node 1, w_run is executed, which reads the west.h5, select one job and mark it as running and then start this job.
At the same time, w_run is executed on node 2, which tried to select the first job but found that it has been marked, so it selects the next job, mark it as running and then start the job.

Hours later, node 1 finish the job, write the result to the west.h5 and try to select the next job, found it to be marked, goes to job 3 and then mark it and start the job.
