### ISSUE TITLE
Update setup.sh to pull proper revision of west_tools

### ISSUE THREAD

**Issue by ajoshpratt** [westpa/westpa#15]
We've made numerous updates to the west_tools repo, but the setup.sh is currently set to pull an older version of the repository.

I'm assuming this is (or was) considered a safety feature, but is it still necessary, in general?  If we're pushing to the main subrepos, in terms of wwmgr and west_tools, we clearly consider the code 'good enough'.

At any rate, I'm willing to push to an update to setup.sh to ensure we're pulling the most recent version of west_tools (fdc0378aecb5f1b1986237c3b170e91239867cd1, or the merging of the yaml_branch).  Alternatively, we could remove the part of the line that pulls a particular commit altogether, and just clone the repo as it stands.

Adam

**Comment by synapticarbors** [comment]
@ajoshpratt When we moved to git/github `wwmgr` and `west_tools` ceased to be bonafide subrepos in the sense that they were under mercurial. Now they are just independent repos. The advanced user could always `git fetch` and then `git merge` the latest changesets. But since we don't have something like a development and release branch (everything gets merged back into the default branch immediately after testing), the `setup.sh` fixes the release tag for general users who would never manually update the other repos.

**Comment by ajoshpratt** [comment]
Do you mean release tag as in, the user is able to say, 'oh, I used this set of software for this run'?

That makes sense, and implies we should simply update the setup.sh file when we merge changes into the independent repos, which we haven't done in a bit.  Unless there is a compelling reason not to (such as 'only updating on major releases', etc, which I don't think we're really doing?).

**Comment by ajoshpratt** [comment]
No longer relevant, as west_tools is now merged in with westpa.
