### ISSUE TITLE
nacl_amb example requires modification of env.sh to work

### ISSUE THREAD

**Issue by synapticarbors** [westpa/westpa#24]
In the `env.sh` file in the nacl_amb example, there is no attempt to automatically detect where Amber is installed on a user's system:

https://github.com/westpa/westpa/blob/master/lib/examples/nacl_amb/env.sh#L5

The example therefore, does not work right out of the box, but there is no indication that the user needs to make any modifications before attempting to run the example. There also isn't any indication of this in the tutorial:

https://westpa.github.io/westpa/tutorials/amber.html

The example should be modified to attempt to automatically find the amber install and if it can't, print a useful error message.

**Comment by ajoshpratt** [comment]
I think Amber always requires $AMBERHOME to be set, so we should probably make it use that instead of `which`.  Unless the local sysadmin has been behaving badly and not setting the variable within the environment module, which is possible.

But using $AMBERHOME/bin would allow them to use the amber.sh script that Amber suggests they use, so that's probably still the way to go.  We could set CPPTRAJ and PMEMD to $AMBERHOME/bin/cpptrajorpmemd, check if that exists, then just try `which` if it fails (IE, a last ditch effort, if they've just forced the Amber path into their $PATH variable).
