### ISSUE TITLE
plothist doesn't work when setting pcoord_len=1 in west.cfg

### ISSUE THREAD

**Issue by razvanmarinescu** [westpa/westpa#290]
I have been running long simulations with WESTPA and generated around 1TB in a single simulation, so I'm trying to cut down on the space. I thus set `pcoord_len=1 ` in `west.cfg`, and also set that the simulation only saves **one** (final) step in run_md.py:

```
simulation.reporters.append(DCDReporter('seg.dcd', 25000))
simulation.step(25000)
simulation.saveState('seg.xml')
```
It all works, the segments move properly over many iterations, and I can see the correct progress coordinates with find_pcoord.py. However, the command `plothist evolution pdist.h5` gives me an empty plot:

![Screen Shot 2023-01-08 at 8 09 02 AM](https://user-images.githubusercontent.com/2820475/211207000-0a7dcc0f-bb7e-42e3-993f-317a11b09418.png)

Any ideas? Also, I can confirm that when I save two steps instead of one, it works! So I think there's a small bug once the array becomes one-dimensional.

**Comment by razvanmarinescu** [comment]
Edit: did some digging and it seems the problem is here when loading the h5 file:
```
hists_ds = self.input_h5['histograms']
```
This array contains nan's for the second iteration, as follows:
```
hists_ds [[0.33238659 0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.33238659 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.33238659 0.66477319 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [       nan        nan        nan        nan        nan        nan
         nan        nan        nan        nan        nan        nan
         nan        nan        nan        nan        nan        nan
         nan        nan        nan        nan        nan        nan
         nan        nan        nan        nan        nan        nan
         nan        nan        nan        nan        nan        nan
         nan        nan        nan        nan        nan        nan
         nan        nan        nan        nan        nan        nan
         nan        nan        nan        nan        nan        nan
         nan        nan        nan        nan        nan        nan
         nan        nan        nan        nan        nan        nan
         nan        nan        nan        nan        nan        nan
         nan        nan        nan        nan        nan        nan
         nan        nan        nan        nan        nan        nan
         nan        nan        nan        nan        nan        nan
         nan        nan        nan        nan        nan        nan
         nan        nan        nan        nan]]

**Comment by jeremyleung521** [comment]
Hi Dr. Razvan (@razvanmarinescu),

I can reproduce what you're seeing. Here are a few things around your problems.

### w_pdist + plothist
This is by design of `w_pdist` to require at least 2 frames. When saving a `pcoord` dataset, it is important to save at least  the last frame of its _parent segment_ + the last frame of the _current segment_ to include the effects of resampling. I believe all of WESTPA's analysis tools assumes the parent pcoord is included as the first data point. This can be achieved by also loading in the parent structure when calculating the pcoord in `runseg.sh`. Post simulation, I would suggest looping through your segments and appending the extra frame into the `west.h5` file.

From Page 7 of the tutorial: https://github.com/westpa/westpa_tutorials/blob/main/paper/TutorialManuscript.pdf
> Also remember that you must include the
parent coordinate file as your first data point when storing the
progress coordinate data. This will ensure that the analysis
tools work properly.

If you really do need to plot it, you can use `wedap`, a plotting tool @darianyang (a fellow Chong Lab member) developed. [Link here](https://github.com/darianyang/wedap). While the output will be reasonable, this would likely produce a different graph that that if it is generated from data that included the parent frame.
To install:
`pip install wedap`
To quickly plot:
`wedap -h5 west.h5`

### To save space: 
There are other more efficient ways of trimming down on simulation size. H5 files are generally quite compact already.
1. You can use the HDF5 Framework (Section 3.1) as introduced in our [second tutorial manuscript](https://github.com/westpa/westpa2_tutorials/blob/main/paper/AdvancedTutorialManuscript.pdf)

2. Tar up the trajectory files by iterations using these lines in `westpa_scripts/post_iter.sh`:
```
ITER=$(printf "%06d" $WEST_CURRENT_ITER)
TAR=$(($WEST_CURRENT_ITER-1))
TAR_DIR=$(printf "%06d" $TAR)
echo $ITER
echo $TAR
echo $TAR_DIR
tar -cf seg_logs/$ITER.tar seg_logs/$ITER-*.log
rm  -f  seg_logs/$ITER-*.log
if [ -d traj_segs/$TAR_DIR ]; then
  tar -cf traj_segs/$TAR_DIR.tar traj_segs/$TAR_DIR
  rm -rf traj_segs/$TAR_DIR
fi
```

### Last FYI
Next time it might be quicker to post in the mailing list. Some of the others in the lab are not subscribed to the GitHub Issues and thus may result in slower replies.

-- JL

**Comment by razvanmarinescu** [comment]
Thanks so much Jeremy. 

> There are other more efficient ways of trimming down on simulation size. H5 files are generally quite compact already.

On that, I think I'm already using the HDF5 framework. This is how my traj_segs folder looks:

```
(raz-westpa-dev) razvanm@perlmutter:login08:~/community/10mer2D> d traj_segs/
total 135G
drwxrwx--- 85 razvanm  16K Jan 10 10:27 000189
drwxrwx---  3 razvanm  16K Jan 10 10:27 .
-rw-rw----  1 razvanm 701M Jan 10 10:27 iter_000188.h5
-rw-rw----  1 razvanm 701M Jan 10 10:24 iter_000187.h5
-rw-rw----  1 razvanm 701M Jan 10 10:20 iter_000186.h5
-rw-rw----  1 razvanm 701M Jan 10 10:17 iter_000185.h5
-rw-rw----  1 razvanm 701M Jan 10 10:13 iter_000184.h5
...
```

It's a list of h5 files. Also, at each iterations I save only two timepoints (the parent, and the final step). Is there anything else I can do to reduce the file size? **Can I do that tar strategy you mentioned on top of this HDF5**?

**Comment by jeremyleung521** [comment]
Hi Dr. Razvan,

Tarring the H5 files will probably give you very little gain. Though 700MB / iteration isn't extraordinarily big by WE simulations standards.

### Stripping water
If your system contains a lot of explicit water molecules which are not essential to the process you're looking at, you can strip them out before passing the trajectory to the per-iter H5 file in `runseg.sh` (pass a stripped parm file there as well). Make sure you include the waters in the restart file though, as they're essential for starting the next iteration. How much space this will save will depend on how big your system is. 

Though I do recall mismatched parm files causing some troubles with the trajectory objects in the `westpa.analysis` module so it will definitely depend on your use case. Sometimes not using the HDF5 Framework + stripping the water + tarring it (like I suggested earlier) might yield better results and are easier to handle file-management-wise.

### Other Ideas
You can also consider lowering the number of segs/bin, or lower the number of bins overall to reduce the number of segments to fit your storage criteria. We've also had success saving space by storing larger dimensional arrays into a 1D array for storage in auxdata (including coordinates). You can reshape it when needed.

-- JL
