### ISSUE TITLE
Callback error when different registered callbacks have the same priority and name 

### ISSUE THREAD

**Issue by synapticarbors** [westpa/westpa#409]
This came up in an question on the mailing list, and looking at the code, I can see a bug in the logic. 

The failing line is:

```
File "/home/abc/anaconda3/envs/westpa-2020.05/westpa-2020.05/src/west/sim_manager.py", line 114, in invoke_callbacks
    sorted_callbacks = sorted(callbacks)
TypeError: '<' not supported between instances of 'method' and 'method'
```

`callbacks` should be a set of tuple of `(priority, function.__name__, function)`. Priority should b an int, `function.__name__` should be a string, and `function` is a method. This should work as long as the pair of `priority` and `function.__name__` are unique. The problem is is that you should never compare functions in the call to `sorted`, because this throws the above error. For example:

```python
import math

x = set([(0, 'foo', math.cos), (0, 'foo', math.sin)])
y = sorted(x)
```

errors with:

```
TypeError: '<' not supported between instances of 'builtin_function_or_method' and ‘builtin_function_or_method'
```

So what looks to be happening is that there are callbacks being registered that have the same priority and name. The code here can error whenever this happens, which isn’t good. It should probably be fixed to at least warn users that callbacks have been registered with duplicate (priority, name). You could also change the `sorted(callbacks)` to `sorted(callbacks, key=operator.itemgetter(0, 1))` to only sort on the priority and name.

**Comment by jeremyleung521** [comment]
After some digging and testing, It seems like @jdrusso plugged this bug in https://github.com/westpa/westpa/issues/182 for WESTPA 2.0: by prioritizing the existing callback with the same name and ignoring the subsequent adds, [lines here](https://github.com/westpa/westpa/blob/westpa2/src/westpa/core/sim_manager.py#L111-L127).

This could be overly broad, as callbacks with same name could be completely different (as see in the mailing list where the same callback are from two different plugins). Modified the [try/except/else block](https://github.com/westpa/westpa/pull/410/files#diff-72c2c83ebfdf534badc6cf38196b1815d12c290ac19965c88616ccb285d6b79aR124-R130) such that it'll skip functions with the same hash in #410. This PR will also include the sorted key fix + warning when multiple callbacks have the same priority.

WESTPA 1.0 (#411) will retain current behavior by not checking any duplicate callbacks (i.e. just include what @synapticarbors suggested). This is because WESTPA 1.0 is deprecated.

**Comment by jeremyleung521** [comment]
Merged and released.
