### ISSUE TITLE
WEST_CURRENT_SEG_ID seems broken

### ISSUE THREAD

**Issue by fabian-paul** [westpa/westpa#84]
Hi all,

I keep seeing WEST_CURRENT_SEG_ID set to -1 in my runs. According to the [documentation](https://chong.chem.pitt.edu/wewiki/Environment_variables), this is not a valid value.

I think the problem lies in the line

https://github.com/westpa/westpa/blob/ba33dc3dd31de034eb23638ad234629a8aaca11f/src/west/propagators/executable.py#L322

which uses a too general if condition that eventually replaces every 0 by a -1.

```Python
>>> str(0 or -1)
'-1'
```
I can follow up with a PR.

Best,
Fabian

**Comment by fabian-paul** [comment]
I wonder what would be the best fix. I think that one can just delete the `or -1` part. On the next line in the code, there is a call to `self.makepath` where it is assumed that `segment.seg_id` is valid. So if `segment.seg_id` was `None` the code would crash anyway on the next line. Therefore I would delete the or.

There is a similar pattern in the initialization of two other environment variables both which are not allowed to be negative according to the documentation. There, I would delete the `or -1` as well.

https://github.com/westpa/westpa/blob/e74e01b8f86e00253dce251ce092880bb06e3a59/src/west/propagators/executable.py#L262

https://github.com/westpa/westpa/blob/e74e01b8f86e00253dce251ce092880bb06e3a59/src/west/propagators/executable.py#L270

**Comment by ASinanSaglam** [comment]
I suspect this was originally written for 1-indexed values (which would be true for, say, the iteration numbers) and it would work in that case. I think this is there to avoid ```None``` or similar values being passed around and we should still attempt to avoid that and removing the ```or -1``` statement doesn't work in that case. I'd say it's better for both making it clear where the code fails and we can also consistently fix the lines 262 and 270 as well since those are not used for making paths.

I'm not immediately sure about the exact solution but something like calling isinstance(value, int) to ensure they are integer values to ensure these values are not set to some insane value might work since we do expect these values to be integers anyway. I'm sure I'm missing some edge cases at the moment though.

**Comment by fabian-paul** [comment]
Well, I would not assume that `segment.seg_id` can be of any random type. Ideally it's always a python integer type (or `None`?). 
If `segment.seg_id` is None, converting it to a string with `str` is ok, the result is just `'None'`. I think getting `'None'` in the shell script is as confusing as getting -1.
Possible even using `str` to do the conversion is too permissive and might hide potential bugs. Probably the the better conversion is `'%d'%segment.seg_id`

**Comment by mczwier** [comment]
String formatting is probably the way to go here, and the point is to avoid
None. I'm extremely hesitant to use isinstance() because that makes
assumptions about how the Python typing system interacts with Numpy
interacts with h5py, which is fragile.

I do have a sneaking suspicion that seg_id==None is an edge case that
matters, or at least mattered at one point in WESTPA development. If it
still matters anywhere, it would be for basis state or initial state
calculations, and it would be explicitly signaling that this is not a
propagation segment to the child executable. So let's not overpatch this.
String formatting will cover this well, correctly turning a seg_id of 0
into a textual zero. As far as putting -1 into the environment goes, it
should probably stay, as an explicit test for None. Otherwise, eliminate
all -1 references and test the hell out of it to make sure you haven't
swapped one corner-case bug for another.

**Comment by mczwier** [comment]
Sorry. `seg_id is None`, not ==None

**Comment by ASinanSaglam** [comment]
Definitely fair point, I agree it's likely a bad idea to test it with something like isinstance or something along those lines. String formatting sounds like a good way to solve the issue from what I can tell too.

**Comment by fabian-paul** [comment]
Ok, I've opened a PR with a conservative fix that follows @mczwier's suggestion.
