### ISSUE TITLE
restart_plugin.py for OpenMM does not work correctly after restarting simulation

### ISSUE THREAD

**Issue by jdrusso** [westpa/westpa#91]
Hi,

I'm using the 2017.10 release, that contains the nacl_openmm example. This contains a plugin, '[restart_plugin.py](https://github.com/westpa/westpa/blob/v2017.10/lib/examples/nacl_openmm/restart_plugin.py)' which is supposed to handle restarting trajectories in a new iteration.

However, this seems to choke when restarting a simulation that was prematurely cancelled.

```
Exception caught; shutting down
-- ERROR    [w_run] -- Traceback (most recent call last):
  File "/home/groups/ZuckermanLab/russojd/miniconda/envs/westpa-clean/westpa-2017.10/lib/cmds/w_run.py", line 65, in <module>
    sim_manager.run()
  File "/home/groups/ZuckermanLab/russojd/miniconda/envs/westpa-clean/westpa-2017.10/src/west/sim_manager.py", line 646, in run
    self.propagate()
  File "/home/groups/ZuckermanLab/russojd/miniconda/envs/westpa-clean/westpa-2017.10/src/west/sim_manager.py", line 491, in propagate
    incoming = future.get_result()
  File "/home/groups/ZuckermanLab/russojd/miniconda/envs/westpa-clean/westpa-2017.10/lib/wwmgr/work_managers/core.py", line 343, in get_result
    raise self._exception
Exception: Particle coordinate is nan
```

To reproduce: Run the nacl_openmm example, interrupt it, and restart it with `w_run`.

**Comment by atbogetti** [comment]
Hello,
We are in the process of updating the tutorials included in the example directory of the WESTPA conda installation.  The openmm tutorial you are using is not supported anymore and we have provided an updated one [here](https://github.com/westpa/westpa/tree/master/lib/examples).  The new openmm tutorial with nacl is titled: basic_nacl.  Please use that tutorial instead of the ones included in the conda installation for now.  The issue you describe should not be present in the new tutorial.

**Comment by jdrusso** [comment]
Technically I guess it's not present in the new tutorial code, since it seems like the functionality provided by `restart_plugin.py` was just removed. Is there something else that provides the ability to start new segments without writing any new files?

**Comment by synapticarbors** [comment]
@jdrusso - The "Particle coordinate is nan" exception seems to be originating on the OpenMM side of things and according to an issue on the OpenMM github issue tracker, it indicates that the simulation blew up for some reason. My suspicion however, is that somewhere in the code, the data for the coords and/or velocities are being initialized using `np.empty` and when the simulation exits prematurely, it is left just holding garbage data, which causes OpenMM to barf on some unphysical state.  Glancing at the code (which I probably last looked at over 6 years ago), I can't immediately see where this might be happening since a segment looks like it should get full and proper coords before it is ever marked "complete", so I could be wrong. 

My recommendation would be to inspect the .h5 file, possibly dumping the coords for the segment that is crashing, and seeing if the coords and velocities look reasonable. You could also just use `w_truncate` to get rid of the last partially completed iteration and see if if you can cleanly restart.

**Comment by jdrusso** [comment]
Thanks for the response! Your thoughts on it blowing up are pretty aligned with the hunches I had about it. It's possibly worth adding that I ran this system for a few hundred iterations multiple times with no problems, but it would consistently choke after being restarted.

I'll take a look at the last frame of the h5, and really appreciate the tip on `w_truncate`, that's very helpful.

**Comment by jdrusso** [comment]
`w_truncate` works excellently as a workaround. Given the lengths of my iterations, it's fine to discard some partial progress within an iteration for a restart.

Thanks again!
