### ISSUE TITLE
Installing westpa in ppc64le architectures?

### ISSUE THREAD

**Issue by kyriegorrin** [westpa/westpa#92]
Dear devs,

I was wondering if it would be possible to install westpa to a PowerPC architecture (ppc64le), seeing that all installation methods provided involve conda and the conda-forge channels for ppc64le don't include the package:

Can't find westpa here:
- https://conda.anaconda.org/conda-forge/linux-ppc64le
- https://conda.anaconda.org/conda-forge/noarch

I've been able to install it successfully in a x86-64 based architecture (it can find the package without problems), but I haven't been able to do it for ppc64le.

Is there any functional workaround to this or is this a dead end?

Thanks.

**Comment by synapticarbors** [comment]
WESTPA cannot be built for the `noarch` channel since it compiles platform dependent C-extensions. I took a quick glance at the packages in `linux-ppc64le` and it looks like all of the dependencies are theoretically there. I would just need to look into what needs to be done to modify the build scripts to have it produce binaries based on that architecture, but a quick search online found the following blog post that might provide you a path to do it yourself before we figure out how to formally do this and discuss if this is something we want to support:

https://developer.ibm.com/linuxonpower/2019/08/30/community-built-python-packages-for-power-systems-in-conda-forge/

**Comment by synapticarbors** [comment]
As an experiment, since the changes required seem minimal, I attempting to build the westpa feedstock for ppc64le in https://github.com/conda-forge/westpa-feedstock/pull/9

**Comment by synapticarbors** [comment]
As an update, having talked to one of the other conda-forge core developers, conda-forge only supports `ppc64le` for python3. So this will have to wait until westpa releases the python3 update.

**Comment by kyriegorrin** [comment]
Thanks for the insight, I really appreciate the effort. Don't worry then, I'll wait for the ptyhon3 update in this case, seeing that . We'll be using the x86-64 version as a workaround in the meantime, seeing that the bottleneck is the unavailability of a python3 version for the moment.

Thanks again for everything.

**Comment by synapticarbors** [comment]
closed by https://github.com/conda-forge/westpa-feedstock/pull/21. The builds should be available on anaconda.org through the conda-forge channel shortly.
