### ISSUE TITLE
Missing iteration data from west.h5

### ISSUE THREAD

**Issue by castephens** [westpa/westpa#95]
Hi, I've been try to access information from my west.h5 for a specific iteration, not my last iteration (274/300 iteration), it doesn't seem to exist. 

This is what I'm running:
DataIn = h5py.File("./west.h5", 'r')
i=274
ITER = "{0:08}".format(i)
SegNum = int(DataIn["/iterations/iter_"+ITER+"/pcoord"].shape[0])

I get this error:
Traceback (most recent call last):
  File "get_target_trajs.py", line 23, in <module>
    SegNum = int(DataIn["/iterations/iter_"+ITER+"/pcoord"].shape[0])
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/cstephens/miniconda3/envs/westpa-2017.10/lib/python2.7/site-packages/h5py/_hl/group.py", line 167, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: 'Unable to open object (message type not found)'

Is there a way to recover information about this iteration and its segments (parents, weights, PCs, ect.) or build a new .h5 file? Thanks!

**Comment by castephens** [comment]
1. It only fails for 274. 
2. Output for 273 DataIn['iterations']['iter_0000%04d'%i].keys():
     [u'bin_target_counts', u'ibstates', u'pcoord', u'seg_index', u'wtgraph']

**Comment by synapticarbors** [comment]
That seems strange that a single iteration should fail like that and how the simulation would then continue with the missing data to restart the next iteration. Is it possible that that iteration was somehow deleted outside of the running WE simulation during analysis after the fact?

It's been a while since I looked at westpa in detail, but if my memory is correct, the final set of pcoords and other data in an iteration is identical to the first iteration in the subsequent iteration, so you could possibly rebuild some version of iteration 274 using the last slice of data from 273 and the first slice of data from 275. You wouldn't have any intermediate snapshots during the iteration, but that may be ok for what you are doing. Others might have a different idea.

**Comment by castephens** [comment]
Thanks, I actually have all pcoords information and segment trajectories for that iteration, the issue is just that none of the data is in the west.h5 and I need the weights for the trajectories, which I did not originally output in the individual segment directories. Is there any other way to extract the segment weight other than looking at the west.h5 file?
